plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // Selenium WebDriver
    implementation 'org.seleniumhq.selenium:selenium-java:4.20.0'

    implementation 'org.slf4j:slf4j-simple:2.0.7'

    // TestNG
    testImplementation 'org.testng:testng:7.10.1'
}

test {
    useTestNG() {
        suites 'src/test/resources/testng.xml'  // path to your suite file
    }
}