name: Sandbox pipeline
on:
  push:
    branches:
      - develop
jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: ping server
        run: 'curl https://api.ipify.org'
      - name: ping proxy server
        run: 'curl -v https://api.ipify.org'
        env:
          http_proxy: http://8.tcp.ngrok.io:18230
          https_proxy: http://8.tcp.ngrok.io:18230

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Show Chrome version
        run: google-chrome --version

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget 	https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Selenium Tests
        run: ./gradlew test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-report
          path: build/reports/tests/test/index.html
