name: Sandbox pipeline
on:
  push:
    branches:
      - develop
jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: action/checkout@v4
      - name: setup java
        uses: action/setup-java
        with:
          java-version: 17
          distribution: temurin

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Selenium Tests
        run: ./gradlew test